const translations = {
    English: {
      // Navbar
      'navbar.home': 'Home',
      'navbar.events': 'Events',
      'navbar.expiredEvents': 'Expired Events',
      'navbar.createEvent': 'Create Event',
      'navbar.contacts': 'Contacts',
      'navbar.signIn': 'Sign In',
      'navbar.languages': 'Languages',
      'navbar.myEvent': 'My Events',
      'navbar.profile': 'Profile',
      'navbar.logout': 'Logout',
      'navbar.my-participation': 'My Participation',
'profile.edit':'Edit Profile',
'profile.name':'Name',
'profile.created':'Created At',
'profile.save': 'Save Profile',
      
    //   Slider
    'home_slider.1.title':'Discover Amazing Events',
    'home_slider.1.description':'Join the most exciting events in your city and create unforgettable memories.',
    'home_slider.1.buttonText':'Explore Now',

    'home_slider.2.title':'Create Your Own Event',
    'home_slider.2.description':'Host your own events and bring people together for unique experiences',
    'home_slider.2.buttonText':'Start Creating',

    'home_slider.3.title':'Connect with Communities',
    'home_slider.3.description':'Find like-minded people and join communities that share your passions',
    'home_slider.3.buttonText':'Join Now',
       'form.location': 'Location',
          'form.date': 'Date',
          'form.keyword': 'Keyword',
          'form.search': 'Find Events',
    //
    'why_choose_title':'Why Choose EvoKa',
    'why_choose_feture.1.title':'Discover Events',
    'why_choose_feture.1.description':'Find events by city, date, interests within a 50km radius',
    'why_choose_feture.2.title':'Create Events',
    'why_choose_feture.2.description':'Host your own events and manage attendees',
    'why_choose_feture.3.title':'Connect with Others',
    'why_choose_feture.3.description':'Meet people with similar interests',
    'why_choose_feture.4.title':'Free for Individuals',
    'why_choose_feture.4.description':'No hidden charges for personal accounts',
      // Hero
      'hero.title': 'Discover & Create Memorable Events',
      'hero.subtitle': 'Join the community of event enthusiasts',
      'hero.cta': 'Explore Events',
      
      // Features
      'features.title': 'Why Choose EvoKa',
      'features.discover.title': 'Discover Events',
      'features.discover.description': 'Find events by city, date, interests within a 50km radius',
      'features.create.title': 'Create Events',
      'features.create.description': 'Host your own events and manage attendees',
      'features.connect.title': 'Connect with Others',
      'features.connect.description': 'Meet people with similar interests',
      'features.free.title': 'Free for Individuals',
      'features.free.description': 'No hidden charges for personal accounts',
      
      // Auth
      'auth.login': 'Login',
      'auth.signup': 'Sign Up',
      'auth.username': 'Username',
      'auth.email': 'Email',
      'auth.password': 'Password',
      'auth.confirmPassword': 'Confirm Password',
      'auth.telephone': 'Telephone',
      'auth.accountType': 'Account Type',
      'auth.private': 'Private Account (Free)',
      'auth.company': 'Company (Paid)',
      'auth.companyName': 'Company Name',
      'auth.vatNumber': 'VAT Number',
      'auth.address': 'Address',
      'auth.invoicingCode': 'Electronic Invoicing Code',
      'auth.loginWithGoogle': 'Login with Google',
      'auth.loginWithFacebook': 'Login with Facebook',
      'auth.submit': 'Submit',
      
      // Footer
      'footer.about': 'About EvoKa',
      'footer.aboutDescription': 'The ultimate platform to discover, create and attend events in your city. Easily find events based on your interests.',
      'footer.links': 'Useful Links',
      'footer.privacyPolicy': 'Privacy Policy',
      'footer.termsOfService': 'Terms of Service',
      'footer.cookiePolicy': 'Cookie Policy',
      'footer.contact': 'Contact Us',
      'footer.rights': 'All rights reserved',
      'footer.newsletter':'Newsletter',
      'footer.newsletterPlaceholder':'Enter your email address',
      'footer.newsletterSubscribe':'Subscribe',

      'event.Create Your Event': 'Create Your Event',
      'event.Basic Information': 'Basic Information',
      'event.Event Title': 'Event Title',
      'event.Enter event title': 'Enter event title',
      'event.Event Category': 'Event Category',
      'event.Select Category': 'Select Category',
      'event.Conference': 'Conference',
      'event.Workshop': 'Workshop',
      'event.Social': 'Social',
      'event.Description': 'Description',
      'event.Describe your event': 'Describe your event',
      'event.Event Period': 'Event Period',
      'event.Start Date': 'Start Date',
      'event.Start Time': 'Start Time',
      'event.End Date': 'End Date',
      'event.End Time': 'End Time',
      'event.Event Type': 'Event Type',
      'event.Public': 'Public',
      'event.Private': 'Private',
      'event.Notification Email': 'Notification Email',
      'event.Enter notification email': 'Enter notification email',
      'event.Location & Capacity': 'Location & Capacity',
      'event.Address': 'Address',
      'event.Enter city or address': 'Enter city or address',
      'event.Mark Location': 'Mark Location',
      'event.Select a city/address or click/drag the marker to set the exact event location.': 'Select a city/address or click/drag the marker to set the exact event location.',
      'event.Selected': 'Selected',
      'event.Participation': 'Participation',
      'event.Free': 'Free',
      'event.Paid': 'Paid',
      'event.Price': 'Price',
      'event.Enter price': 'Enter price',
      'event.Maximum Participants': 'Maximum Participants',
      'event.Enter max participants': 'Enter max participants',
      'event.Event Images': 'Event Images',
      'event.Additional Documentation': 'Additional Documentation',
      'event.Uploaded': 'Uploaded',
      'event.Creating': 'Creating',
      'event.Create Event': 'Create Event',
      
      'event.My Events':'My Events',
      'event.Category':'Category',
      'event.Start':'Start',
      'event.Status':'Status',
      'event.All Statuses':'All Statuses',
      'event.Pending':'Pending',
      'event.Approved':'Approved',
      'event.Completed':'Completed',
      'event.Rejected':'Rejected',
      'event.No events found. Create your first event':'No events found. Create your first event!',
      'event.View More':'View More',
      'event.Edit':'Edit',
      'event.Edit Event':'Edit Event',
      'event.Save Changes':'Save Changes',
      'event.Cancel':'Cancel',
      'event.Saving':'Saving',
      'event.End':'End',
      'event.Type':'Type',
      'event.Max Participants':'Max Participants',
      'event.Coordinates':'Coordinates',
      'event.pending':'Pending',
      'event.approved':'Approved',
      'event.rejected':'Rejected',
      'event.Location':'Location',
      'event.Close':'Close',
      'event.Images':'Images',
      'event.Document':'Document',
      'event.View Document':'View Document',
     

      'event.Upcoming':'Upcoming',
      'event.Search by event name':'Search by event name',
      'event.Search by city':'Search by city',
      'event.Within 50km of my location':'Within 50km of my location',
      'event.All Events':'All Events',
      'event.No events found. Create a new event':'No events found. Create a new event!',
      
      'event.Rate This Event':'Rate This Event',
      'event.Comments':'Comments',
      'event.Post Comment':'Post Comment',
      'event.Participants':'Participants',
      'event.Participate':'Participate',
      'event.Join Chat Group':'Join Chat Group',
      'event.Add to Google Calendar':'Add to Google Calendar',
      'event.Download Document':'Download Document',
      'event.View':'View Event',
      'event.Rating': 'Rating',
      'event.Posted on': 'Posted on',
      'event.My Participation':'My Participation',
      'event.List of events I participated in':'List of events I participated in',
      'event.Event Name':'Event Name',
      'event.Date n Time':'Date & Time',
      'event.Participated At':'Participated At',
      'event.Go Back to Home':'Go Back to Home',
      'event.No participants yet':'No participants yet',
 'event.Organized By': 'Organized By',
'event.Event Details': 'Event Details',
'event.Fetured Events': 'Fetured Events',
      'event.Add Participants': 'Add Participants',
      'event.Participant Name': 'Participant Name',
      'event.Enter participant name': 'Enter participant name',
      'event.Email': 'Email',
      'event.Enter email': 'Enter email',
      'event.Optional': 'Optional',
      'event.Remove participant': 'Remove participant',
      'event.Add Another Participant': 'Add Another Participant',
      'event.Booking Summary': 'Booking Summary',
      'event.Total Participants': 'Total Participants',
      'event.Tickets': 'Tickets',
      'event.Total Amount': 'Total Amount',
      'event.Total Cost': 'Total Cost',
      'event.Book Tickets': 'Book Tickets',
      'event.Processing...': 'Processing...',
      'event.Please add at least one participant': 'Please add at least one participant',
      'event.Participant names must be unique': 'Participant names must be unique',
      'event.Participation successful': 'Participation successful',

      'Apply Promo Code': 'Apply Promo Code',
      'Choose Your Subscription Plan': 'Choose Your Subscription Plan',
      'Active Plan': 'Active Plan',
      'Active': 'Active',
      'Months': 'Months',
      'Subscribe': 'Subscribe'
    },
    Italian: {
      // Navbar
      'navbar.home': 'Home',
      'navbar.events': 'Eventi',
      'navbar.expiredEvents': 'Eventi Scaduti',
      'navbar.createEvent': 'Crea Evento',
      'navbar.contacts': 'Contatti',
      'navbar.signIn': 'Accedi',
      'navbar.languages': 'Lingue',
      'navbar.myEvent': 'I miei eventi',
            'navbar.my-participation': 'La mia partecipazione',

'navbar.profile': 'Profilo',
'navbar.logout': 'Disconnettersi',
'profile.edit': 'Modifica Profilo',
'profile.name': 'Nome',
'profile.created': 'Creato Il',
'profile.save': 'Salva profilo',

    //   Slider
    'home_slider.1.title': 'Scopri Eventi Straordinari',
    'home_slider.1.description': 'Partecipa agli eventi più emozionanti della tua città e crea ricordi indimenticabili.',
    'home_slider.1.buttonText': 'Esplora Ora',

    'home_slider.2.title': 'Crea il Tuo Evento',
    'home_slider.2.description': 'Organizza i tuoi eventi e unisci le persone per esperienze uniche.',
    'home_slider.2.buttonText': 'Inizia a Creare',

    'home_slider.3.title': 'Connettiti con le Comunità',
    'home_slider.3.description': 'Trova persone con gli stessi interessi e unisciti a comunità che condividono le tue passioni.',
    'home_slider.3.buttonText': 'Unisciti Ora',

    'form.location': 'Luogo',
    'form.date': 'Data',
    'form.keyword': 'Parola chiave',
    'form.search': 'Trova Eventi',
// 
'why_choose_title': 'Perché Scegliere EvoKa',
'why_choose_feture.1.title': 'Scopri Eventi',
'why_choose_feture.1.description': 'Trova eventi per città, data, interessi entro un raggio di 50 km',
'why_choose_feture.2.title': 'Crea Eventi',
'why_choose_feture.2.description': 'Organizza i tuoi eventi e gestisci i partecipanti',
'why_choose_feture.3.title': 'Connettiti con Altri',
'why_choose_feture.3.description': 'Incontra persone con interessi simili',
'why_choose_feture.4.title': 'Gratis per Privati',
'why_choose_feture.4.description': 'Nessun costo nascosto per account personali',

      // Hero
      'hero.title': 'Scopri e Crea Eventi Memorabili',
      'hero.subtitle': 'Unisciti alla community degli appassionati di eventi',
      'hero.cta': 'Esplora Eventi',
      
      // Features
      'features.title': 'Perché Scegliere EvoKa',
      'features.discover.title': 'Scopri Eventi',
      'features.discover.description': 'Trova eventi per città, data, interessi entro 50 km',
      'features.create.title': 'Crea Eventi',
      'features.create.description': 'Organizza i tuoi eventi e gestisci i partecipanti',
      'features.connect.title': 'Connettiti con Altri',
      'features.connect.description': 'Incontra persone con interessi simili',
      'features.free.title': 'Gratuito per Privati',
      'features.free.description': 'Nessun costo nascosto per account personali',
      
      // Auth
      'auth.login': 'Accedi',
      'auth.signup': 'Registrati',
      'auth.username': 'Nome Utente',
      'auth.email': 'Email',
      'auth.password': 'Password',
      'auth.confirmPassword': 'Conferma Password',
      'auth.telephone': 'Telefono',
      'auth.accountType': 'Tipo di Account',
      'auth.private': 'Account Privato (Gratuito)',
      'auth.company': 'Azienda (A Pagamento)',
      'auth.companyName': 'Nome Azienda',
      'auth.vatNumber': 'Partita IVA',
      'auth.address': 'Indirizzo',
      'auth.invoicingCode': 'Codice Fatturazione Elettronica',
      'auth.loginWithGoogle': 'Accedi con Google',
      'auth.loginWithFacebook': 'Accedi con Facebook',
      'auth.submit': 'Invia',
      
      // Footer
      'footer.about': 'Chi è EvoKa',
      'footer.aboutDescription': 'La piattaforma definitiva per scoprire, creare e partecipare agli eventi nella tua città. Trova facilmente eventi in base ai tuoi interessi.',
      'footer.links': 'Link Utili',
      'footer.privacyPolicy': 'Politica sulla Privacy',
      'footer.termsOfService': 'Termini di Servizio',
      'footer.cookiePolicy': 'Politica dei Cookie',
      'footer.contact': 'Contattaci',
      'footer.rights': 'Tutti i diritti riservati',

      'footer.newsletter':'Notiziario',
      'footer.newsletterPlaceholder':'Inserisci il tuo indirizzo email',
      'footer.newsletterSubscribe':'Iscriviti',

      'event.Create Your Event': 'Crea il tuo evento',
'event.Basic Information': 'Informazioni di base',
'event.Event Title': 'Titolo dell\'evento',
'event.Enter event title': 'Inserisci il titolo dell\'evento',
'event.Event Category': 'Categoria dell\'evento',
'event.Select Category': 'Seleziona categoria',
'event.Conference': 'Conferenza',
'event.Workshop': 'Laboratorio',
'event.Social': 'Sociale',
'event.Description': 'Descrizione',
'event.Describe your event': 'Descrivi il tuo evento',
'event.Event Period': 'Periodo dell\'evento',
'event.Start Date': 'Data di inizio',
'event.Start Time': 'Ora di inizio',
'event.End Date': 'Data di fine',
'event.End Time': 'Ora di fine',
'event.Event Type': 'Tipo di evento',
'event.Public': 'Pubblico',
'event.Private': 'Privato',
'event.Notification Email': 'Email di notifica',
'event.Enter notification email': 'Inserisci l\'email di notifica',
'event.Location & Capacity': 'Posizione e capacità',
'event.Address': 'Indirizzo',
'event.Enter city or address': 'Inserisci città o indirizzo',
'event.Mark Location': 'Segna posizione',
'event.Select a city/address or click/drag the marker to set the exact event location.': 'Seleziona una città/indirizzo o fai clic/trascina il marcatore per impostare la posizione esatta dell\'evento.',
'event.Selected': 'Selezionato',
'event.Participation': 'Partecipazione',
'event.Free': 'Gratuito',
'event.Paid': 'A pagamento',
'event.Price': 'Prezzo',
'event.Enter price': 'Inserisci il prezzo',
'event.Maximum Participants': 'Numero massimo di partecipanti',
'event.Enter max participants': 'Inserisci il numero massimo di partecipanti',
'event.Event Images': 'Immagini dell\'evento',
'event.Additional Documentation': 'Documentazione aggiuntiva',
'event.Uploaded': 'Caricato',
'event.Creating': 'Creazione in corso',
'event.Create Event': 'Crea evento',


'event.My Events': 'I miei eventi',
'event.Category': 'Categoria',
'event.Start': 'Inizio',
'event.Status': 'Stato',
'event.All Statuses': 'Tutti gli stati',
'event.Pending': 'In attesa',
'event.Approved': 'Approvato',
'event.Completed': 'Completato',
'event.Rejected': 'Rifiutato',
'event.No events found. Create your first event': 'Nessun evento trovato. Crea il tuo primo evento!',
'event.View More': 'Vedi di più',
'event.Edit': 'Modifica',
'event.Edit Event': 'Modifica evento',
'event.Save Changes': 'Salva modifiche',
'event.Cancel': 'Annulla',
'event.Saving': 'Salvataggio in corso',
'event.End': 'Fine',
'event.Type': 'Tipo',
'event.Max Participants': 'Numero massimo di partecipanti',
'event.Coordinates': 'Coordinate',
'event.pending': 'In attesa',
'event.approved': 'Approvato',
'event.rejected': 'Rifiutato',
'event.Location': 'Posizione',
'event.Close': 'Chiudi',
'event.Images': 'Immagini',
'event.Document': 'Documento',
'event.View Document': 'Visualizza documento',


'event.Upcoming': 'In arrivo',
'event.Search by event name': 'Cerca per nome evento',
'event.Search by city': 'Cerca per città',
'event.Within 50km of my location': 'Entro 50 km dalla mia posizione',
'event.All Events': 'Tutti gli eventi',
'event.No events found. Create a new event': 'Nessun evento trovato. Crea un nuovo evento!',

'event.Rate This Event': 'Valuta questo evento',
'event.Comments': 'Commenti',
'event.Post Comment': 'Pubblica commento',
'event.Participants': 'Partecipanti',
'event.Participate': 'Partecipa',
'event.Join Chat Group': 'Unisciti al gruppo chat',
'event.Add to Google Calendar': 'Aggiungi a Google Calendar',
'event.Download Document': 'Scarica documento',
'event.View': 'Visualizza evento',
      'event.Rating': 'Valutazione',
      'event.Posted on': 'Pubblicato su',
'event.My Participation': 'La Mia Partecipazione',
'event.List of events I participated in': 'Elenco degli eventi a cui ho partecipato',
'event.Event Name': 'Nome dell\'Evento',
'event.Date n Time': 'Data e Ora',
'event.Participated At': 'Partecipato il',
'event.Go Back to Home': 'Torna alla Home',
      'event.No participants yet':'Nessun partecipante ancora',
 'event.Organized By': 'Organizzato da',
 'event.Event Details': 'Dettagli dell\'evento',
'event.Fetured Events': 'Eventi in evidenza',
      'event.Add Participants': 'Aggiungi Partecipanti',
      'event.Participant Name': 'Nome Partecipante',
      'event.Enter participant name': 'Inserisci nome partecipante',
      'event.Email': 'Email',
      'event.Enter email': 'Inserisci email',
      'event.Optional': 'Opzionale',
      'event.Remove participant': 'Rimuovi partecipante',
      'event.Add Another Participant': 'Aggiungi Altro Partecipante',
      'event.Booking Summary': 'Riepilogo Prenotazione',
      'event.Total Participants': 'Totale Partecipanti',
      'event.Tickets': 'Biglietti',
      'event.Total Amount': 'Importo Totale',
      'event.Total Cost': 'Costo Totale',
      'event.Book Tickets': 'Prenota Biglietti',
      'event.Processing...': 'Elaborazione...',
      'event.Please add at least one participant': 'Aggiungi almeno un partecipante',
      'event.Participant names must be unique': 'I nomi dei partecipanti devono essere unici',
      'event.Participation successful': 'Partecipazione riuscita',
  "Apply Promo Code": "Applica Codice Promozionale",
  "Choose Your Subscription Plan": "Scegli il Tuo Piano di Abbonamento",
  "Active Plan": "Piano Attivo",
  "Active": "Attivo",
  "Months": "Mesi",
  "Subscribe": "Abbonati"
 
    }
  };

function getTranslation(lang, key) {
    if (translations[lang] && translations[lang][key]) {
      return translations[lang][key];
    } else {
      // Fallback: return English if key or language not found
      return translations['English'][key]  || key+'-TF';
    }
  }
  
 export default getTranslation;